### ISSUE TITLE
Upgrade to Micronaut 3.0.x

### ISSUE THREAD

**Issue by msgilligan** [SupernautApp/SupernautFX#17]
Micronaut 3.0.0-M2 is already working on a branch: https://github.com/SupernautApp/SupernautFX/tree/micronaut-3 and no changes were required to use 3.0.x.

The next planned release 0.1.4 should still be on Micronaut 2.5.x.

I assume we'll make a release using Micronaut 3 as soon as it is final.

**Comment by msgilligan** [comment]
It looks like the upgrade from `3.0.0-M2` to `3.0.0-M5` ( 63200fa800abf98099ed4ad5cc70a9ff37579616 ) breaks Micronaut Bean initialization with the runtime error:

``
Exception in thread "SupernautFX-Background-Launcher" io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2692)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1570)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1644)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:257)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
        at io.micronaut.inject@3.0.0-M5/io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:50)
        at app.supernaut.fx.micronaut@0.1.4-SNAPSHOT/app.supernaut.fx.micronaut.MicronautFxLauncher$MicronautAppFactory.<init>(MicronautFxLauncher.java:82)
        at app.supernaut.fx.micronaut@0.1.4-SNAPSHOT/app.supernaut.fx.micronaut.MicronautFxLauncher.lambda$new$0(MicronautFxLauncher.java:49)
        at app.supernaut.fx/app.supernaut.fx.FxLauncherAbstract.startBackgroundApp(FxLauncherAbstract.java:242)
        at app.supernaut.fx/app.supernaut.fx.FxLauncherAbstract.lambda$launchBackgroundApp$0(FxLauncherAbstract.java:223)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

Note that `3.0.0-M3` and `3.0.0-M4` also fail but with a different error.

**Comment by msgilligan** [comment]
See Draft PR #18 for the current `micronaut-3` branch.

**Comment by msgilligan** [comment]
The Sample hello app doesn't work for 3.0.0 GA (or 3.0.0-M3 or later)

See https://github.com/micronaut-projects/micronaut-core/issues/5985

**Comment by msgilligan** [comment]
Still failing in Micronaut 3.0.3, PR #18 has been rebased to use Micronaut 3.0.3. Still waiting for a response from the Micronaut team on https://github.com/micronaut-projects/micronaut-core/issues/5985.
